Introduction to tensors<br>
Manuplulating Tensors<br>
Tensors and Numpy<br>
Excercises<br>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
#creating tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dimensions
scalar.ndim

0

In [ ]:
vector =tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#ceate a matrix
matrix=tf.constant([[2,10],[3,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 3, 11]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix1=tf.constant([[10.,7.],[3.,6.],[9.,7,]],dtype=tf.float16)
matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  6.],
       [ 9.,  7.]], dtype=float16)>

In [ ]:
matrix1.ndim

2

In [ ]:
tensor=tf.constant([[[1,1,1],[2,2,2]],[[1,1,1],[2,2,2]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [2, 2, 2]],

       [[1, 1, 1],
        [2, 2, 2]]], dtype=int32)>

In [ ]:
changable_tensor=tf.Variable([10,7])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
changable_tensor[0].assign(0)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 7], dtype=int32)>

In [ ]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 7], dtype=int32)>

In [ ]:
from tensorflow._api.v2 import random
#Random number
random_tensor=tf.random.Generator.from_seed(43)
ramdom_tensor1=random_tensor.uniform(shape=(3,2))
ramdom_tensor2=random_tensor.normal(shape=(3,2))
ramdom_tensor1,ramdom_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718],
        [0.63932586, 0.6467117 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.54757965,  0.61634356],
        [-0.98912024,  2.0912669 ],
        [ 0.2183963 ,  0.93540764]], dtype=float32)>)

In [ ]:
#shuffle the order
not_shuffled_tensor=tf.constant([[1,2,3],[3,4,5],[3,4,6]])
not_shuffled_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5],
       [3, 4, 6]], dtype=int32)>

In [ ]:
not_shuffled_tensor.ndim

2

In [ ]:
from tensorflow.python.framework import random_seed
#after shuffle
tf.random.set_seed(43)
tf.random.shuffle(not_shuffled_tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 4, 6],
       [1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [ ]:
#tensors using numpy
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## The main difference between a tensor and numpy array is that you can run a tensor in GPU much faster than numpy arrray

In [ ]:
#converting numpy array to tensor
import numpy as np
numpy_array=np.arange(1,25)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
tensor_array=tf.constant(numpy_array,shape=(3,2,4))
tensor_array

<tf.Tensor: shape=(3, 2, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [ ]:
tensor_array2=tf.constant(numpy_array,shape=(2,4,3))

In [ ]:
tensor_array2

<tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

In [ ]:
tf.reshape(tensor_array2,(6,4))

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [ ]:
tf.reshape(tensor_array2,(3,2,2,2))

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])>

In [ ]:
#Tensor Attribute
tensor_array2.shape,tensor_array2.ndim

(TensorShape([2, 4, 3]), 3)

In [ ]:
tensor_array2

<tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

In [ ]:
#first two elements in each dimension
tensor_array2[:2,:2,:2].numpy()

array([[[ 1,  2],
        [ 4,  5]],

       [[13, 14],
        [16, 17]]])

In [ ]:
tensor_array2[:,:1]

<tf.Tensor: shape=(2, 1, 3), dtype=int64, numpy=
array([[[ 1,  2,  3]],

       [[13, 14, 15]]])>

In [ ]:
#Matrix Multiplication
tensor1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor2=tf.constant([[3,5],[6,7],[1,8]])

In [ ]:
result=tf.matmul(tensor1,tensor2)
result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tf.transpose(tensor1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 7, 3],
       [2, 2, 3],
       [5, 1, 3]], dtype=int32)>

In [ ]:
tf.cast(tensor1,dtype=tf.int16)

<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int16)>

In [ ]:
tf.cast(tensor1,dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 5.],
       [7., 2., 1.],
       [3., 3., 3.]], dtype=float32)>

In [ ]:
tensor =tf.constant(np.random.randint(1,100,size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([44, 95, 86, 34, 31, 45, 26, 90, 39, 68, 78,  1, 84, 13, 73, 41, 21,
       34, 46, 47, 95, 44, 61, 94, 94, 85, 99, 15, 30,  7, 80, 62,  8, 30,
       66, 45, 78, 99, 71, 37, 82,  1, 71, 48, 21, 58, 16, 43, 90, 30])>

In [ ]:
#Find the minimum
tf.reduce_min(tensor).numpy()

1

In [ ]:
tf.reduce_max(tensor),tf.reduce_mean(tensor),tf.reduce_sum(tf.cast(tensor,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=53>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2656.0>)

In [ ]:
#variance & standard deviation
import tensorflow_probability as tfp
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=839>

###Positional Minimum and Maximum


In [ ]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)],tf.reduce_max(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [ ]:
#check equality
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.random.set_seed(42)
E=tf.random.uniform(shape=[50])

In [ ]:
for i  in E:
    print(i.numpy())
    break

0.6645621


In [ ]:
E[tf.argmin(E)],tf.reduce_min(E)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [ ]:
tf.random.set_seed(42)
G=tf.random.normal(shape=[50,2])
tf.argmax(G,axis=0)

G[tf.argmax(G,axis=0)[0]][0]

<tf.Tensor: shape=(), dtype=float32, numpy=2.0057273>

###Squeezing a tensor

In [ ]:
H=tf.random.normal(shape=[1,2,20])
tf.squeeze(H)

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[ 8.4224582e-02, -8.6090374e-01,  3.7812304e-01, -5.1962738e-03,
        -4.9453196e-01,  6.1781919e-01, -3.3082047e-01, -1.3840806e-03,
        -4.2373410e-01, -1.3872087e+00, -1.5488191e+00, -5.3198391e-01,
        -4.4756433e-01, -2.0115814e+00, -5.7926011e-01,  5.7938927e-01,
         1.3041967e+00,  6.7720258e-01, -7.4587613e-01,  1.0378964e+00],
       [ 1.3820479e+00,  1.4319171e+00, -3.7643117e-01,  9.8158473e-01,
        -2.3597862e-01, -3.3763260e-01, -8.9593250e-01,  4.2754072e-01,
        -3.8105518e-01,  4.7006992e-01,  3.5413779e-02, -2.9272759e+00,
        -9.6707004e-01, -4.1402709e-01, -4.0137586e-01,  6.2328768e-01,
        -9.3648863e-01,  9.5449388e-01,  4.9025390e-01, -9.9804842e-01]],
      dtype=float32)>

###One hot encoding

In [ ]:
some_list=[[1,2,3],[0,2,3]]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)>